{{- if .Values.priority -}}
{{- $priorities := list "default-priority" "low-priority" "high-priority" -}}
{{- if eq ( has .Values.priority $priorities ) false -}}
{{- fail ( printf "Field 'priority: \"%s\"' in user file is not correctly set (values possible: 'default-priority', 'low-priority', 'high-priority')" .Values.priority ) -}}
{{- end -}}
{{- else -}}
{{ required "Please specify a valid 'priority' in the user file" "" -}}
{{- end -}}

{{- define "priority.className" -}}
{{- if eq .Values.priority "high-priority" -}}
priorityClassName: "high-priority"
{{- else if eq .Values.priority "low-priority" -}}
priorityClassName: "low-priority"
{{- else -}}
priorityClassName: "default-priority"
{{- end -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ required "Please specify a 'name' in the user file" .Values.name }}
    namespace: {{ required "Please specify a 'namespace' in the user file" .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            deployment.apps: susql-controller
    template:
        metadata:
            name: {{ .Values.name }}
            namespace: {{ .Values.namespace }}
            labels:
                deployment.apps: {{ .Values.name }}
        spec:
            {{ include "priority.className" . }}
            serviceAccountName: {{ .Values.name }}
            terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
            containers:
                - name: {{ .Values.name }}
                  image: {{ required "Please specify a 'containerImage' in the user file" .Values.containerImage }}
                  imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
                  args:
                      - "--kepler-prometheus-url={{ .Values.keplerPrometheusUrl }}"
                  resources:
                      requests:
                          cpu: {{ .Values.requests.cpu }}
                          memory: {{ .Values.requests.memory }}
                      limits:
                          cpu: {{ .Values.requests.cpu }}
                          memory: {{ .Values.requests.memory }}
