alertmanager:
    enabled: false
kube-state-metrics:
    enabled: false
prometheus-node-exporter:
    enabled: false
prometheus-pushgateway:
    enabled: false
server:
    name: susql
    priorityClassName: high-priority
    service:
        enabled: true
        type: NodePort
        servicePort: 9090
    persistentVolume:
        existingClaim: prometheus-susql
        enabled: false
    securityContext:
        runAsUser:
        runAsNonRoot:
        runAsGroup:
        fsGroup:
